#lang typed/racket/no-check

(require "../base/enums.rkt")
                                          
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;ENUMS

(define-incr-enum IRobotProjectType
  (I_PT_FRAME_2D 1)
  I_PT_TRUSS_2D
  I_PT_GRILLAGE
  I_PT_FRAME_3D
  I_PT_TRUSS_3D
  I_PT_PLATE
  I_PT_SHELL
  I_PT_AXISYMMETRIC
  I_PT_VOLUMETRIC
  I_PT_CONCRETE_BEAM
  I_PT_CONCRETE_COLUMN
  I_PT_FOUNDATION
  I_PT_PARAMETRIZED
  I_PT_STEEL_CONNECTION
  I_PT_SECTION
  I_PT_PLANE_STRESS
  I_PT_PLANE_DEFORMATION
  I_PT_DEEP_BEAM
  (I_PT_CONCRETE_DEEP_BEAM 18)
  I_PT_BUILDING)


(define-incr-enum IRobotLabelType
  (I_LT_NODE_SUPPORT 0)
  I_LT_NODE_RELEASE
  I_LT_NODE_COMPATIBILITY
  I_LT_BAR_SECTION
  I_LT_BAR_RELEASE
  I_LT_BAR_OFFSET
  I_LT_BAR_CABLE
  I_LT_BAREND_BRACKET
  I_LT_BAR_MATERIAL
  (I_LT_EDGE_SUPPORT 10)
  I_LT_PANEL_THICKNESS
  I_LT_PANEL_REINFORCEMENT
  (I_LT_UNKNOWN -1)
  I_LT_SUPPORT
  (I_LT_MATERIAL 8)
  (I_LT_LINEAR_RELEASE 13)
  I_LT_BAR_ELASTIC_GROUND
  I_LT_NODE_RIGID_LINK
  I_LT_MEMBER_TYPE
  I_LT_VEHICLE
  I_LT_SOLID_PROPERTIES
  I_LT_BAR_GEO_IMPERFECTIONS
  I_LT_BAR_NONLINEAR_HINGE
  I_LT_CLADDING
  I_LT_PANEL_CALC_MODEL
  (I_LT_MEMBER_REINFORCEMENT_PARAMS 25)
  I_LT_COUNT)

(define-incr-enum IRobotMaterialType
  I_MT_ALL
  I_MT_STEEL
  I_MT_CONCRETE
  I_MT_ALUMINIUM
  I_MT_TIMBER
  I_MT_OTHER)

(define-incr-enum IRobotBarSectionType
  I_BST_STANDARD
  I_BST_NS_BOX
  I_BST_NS_I
  I_BST_NS_II
  I_BST_NS_TUBE
  I_BST_NS_RECT
  I_BST_NS_C
  I_BST_NS_L
  I_BST_NS_LP
  I_BST_NS_Z
  I_BST_NS_ZP
  I_BST_NS_T
  I_BST_NS_H
  I_BST_NS_XT
  I_BST_NS_XI
  I_BST_NS_DRECT
  I_BST_NS_CROSS
  (I_BST_NS_HOLE 99)
  (I_BST_COMPLEX 1000)
  (I_BST_NS_BOX_2 17)
  I_BST_NS_POLYGONAL
  (I_BST_SPECIAL 1001)
  I_BST_JOIST
  (I_BST_NS_BOX_3 20))
                
(define-incr-enum IRobotBarSectionShapeType
  (I_BSST_UNKNOWN)
  (I_BSST_CAE)
  (I_BSST_CAEP)
  (I_BSST_CAI)
  (I_BSST_CAIP)
  (I_BSST_DCEC)
  (I_BSST_DCED)
  (I_BSST_DCEP)
  (I_BSST_DCIG)
  (I_BSST_DCIP)
  (I_BSST_HEA)
  (I_BSST_HEAA)
  (I_BSST_HEB)
  (I_BSST_HEC)
  (I_BSST_HEM)
  (I_BSST_HER)
  (I_BSST_HHEA)
  (I_BSST_HHEB)
  (I_BSST_HHEM)
  (I_BSST_IIPE)
  (I_BSST_IPE)
  (I_BSST_IPEA)
  (I_BSST_IPEO)
  (I_BSST_IPER)
  (I_BSST_IPEV)
  (I_BSST_IPN)
  (I_BSST_MHEA)
  (I_BSST_MHEB)
  (I_BSST_MHEM)
  (I_BSST_MIPE)
  (I_BSST_PRS)
  (I_BSST_TCAR)
  (I_BSST_TEAE)
  (I_BSST_TEAI)
  (I_BSST_THEX)
  (I_BSST_TREC)
  (I_BSST_TRON)
  (I_BSST_UAP)
  (I_BSST_UPN)
  (I_BSST_UUAP)
  (I_BSST_UUPN)
  (I_BSST_FRTG)
  (I_BSST_UPAF)
  (I_BSST_BOX 91)
  (I_BSST_RECT)
  (I_BSST_TUBE)
  (I_BSST_ISYM)
  (I_BSST_INSYM)
  (I_BSST_TUSER)
  (I_BSST_CUSER)
  (I_BSST_TBETC)
  (I_BSST_WELD_CROSS 201)
  (I_BSST_DRECT 99)
  (I_BSST_COLD_SIGMA1 1001)
  (I_BSST_COLD_SIGMA2)
  (I_BSST_COLD_ZED1)
  (I_BSST_COLD_U)
  (I_BSST_COLD_CE1)
  (I_BSST_COLD_ANGL)
  (I_BSST_COLD_OMEGA)
  (I_BSST_COLD_SO1)
  (I_BSST_COLD_RIVE1)
  (I_BSST_USER_BOX 91)
  (I_BSST_USER_RECT)
  (I_BSST_USER_TUBE)
  (I_BSST_USER_I_BISYM)
  (I_BSST_USER_I_MONOSYM)
  (I_BSST_USER_T_SHAPE)
  (I_BSST_USER_C_SHAPE)
  (I_BSST_USER_CROSS 201)
  (I_BSST_WOOD_RECT 41)
  (I_BSST_WOOD_DRECT 99)
  (I_BSST_RECT_FILLED 43)
  (I_BSST_CIRC_FILLED)
  (I_BSST_CONCR_COL_R -108)
  (I_BSST_CONCR_COL_T)
  (I_BSST_CONCR_COL_L)
  (I_BSST_CONCR_COL_Z)
  (I_BSST_CONCR_COL_P)
  (I_BSST_CONCR_COL_C)
  (I_BSST_CONCR_COL_CH)
  (I_BSST_CONCR_COL_CQ)
  (I_BSST_CONCR_BEAM_RECT -3)
  (I_BSST_CONCR_BEAM_T)
  (I_BSST_CONCR_BEAM)
  (I_BSST_COMP_2C_FACE 1101)
  (I_BSST_COMP_2C_BACK)
  (I_BSST_COMP_2I)
  (I_BSST_COMP_CI)
  (I_BSST_COMP_2LI)
  (I_BSST_COMP_4L_FACE)
  (I_BSST_COMP_4L_BACK)
  (I_BSST_COMP_2L_SHORT)
  (I_BSST_COMP_2L_LONG)
  (I_BSST_COMP_2L_CROSS)
  (I_BSST_USER_BOX_2 102)
  (I_BSST_CCL 45)
  (I_BSST_URND)
  (I_BSST_TRND)
  (I_BSST_CUAP)
  (I_BSST_WOOD_CIRC 100)
  (I_BSST_USER_CIRC_FILLED)
  (I_BSST_USER_POLYGONAL 103)
  (I_BSST_COLD_C_PLUS 1010)
  (I_BSST_COLD_SIGMA_SL)
  (I_BSST_COLD_SIGMA)
  (I_BSST_COLD_Z)
  (I_BSST_COLD_L_LIPS)
  (I_BSST_COLD_Z_ROT)
  (I_BSST_COMP_2L_FACE_SHORT 1111)
  (I_BSST_COMP_2L_FACE_LONG)
  (I_BSST_COMP_CI_BACK)
  (I_BSST_COMP_2C_FACE_WELD 1201)
  (I_BSST_COMP_2C_BACK_WELD)
  (I_BSST_COMP_2I_WELD)
  (I_BSST_COMP_CI_WELD)
  (I_BSST_COMP_2LI_WELD)
  (I_BSST_COMP_4L_FACE_WELD)
  (I_BSST_COMP_4L_BACK_WELD)
  (I_BSST_COMP_2L_SHORT_WELD)
  (I_BSST_COMP_2L_LONG_WELD)
  (I_BSST_COMP_2L_CROSS_WELD)
  (I_BSST_COMP_2L_FACE_SHORT_WELD)
  (I_BSST_COMP_2L_FACE_LONG_WELD)
  (I_BSST_COMP_CI_BACK_WELD)
  (I_BSST_SPEC_CORRUGATED_WEB 104)
  (I_BSST_SPEC_CASTELLATED_WEB_HEXAGONAL_OPENINGS 50)
  (I_BSST_SPEC_CASTELLATED_WEB_HEXAGONAL_OPENINGS_SHIFTED 52)
  (I_BSST_SPEC_CASTELLATED_WEB_ROUND_OPENINGS 51)
  (I_BSST_CONCR_BEAM_I -4)
  (I_BSST_SPEC_SFB 53)
  (I_BSST_SPEC_IFBA)
  (I_BSST_SPEC_IFBB)
  (I_BSST_JOIST_K 500)
  (I_BSST_JOIST_LH)
  (I_BSST_JOIST_KCS)
  (I_BSST_JOIST_DLH)
  (I_BSST_JOIST_SLH)
  (I_BSST_USER_BOX_3 105)
  (I_BSST_JOIST_G 510)
  (I_BSST_JOIST_VG)
  (I_BSST_JOIST_BG))

(define-incr-enum IRobotBarEndReleaseValue
  (I_BERV_NONE)
  (I_BERV_STD)
  (I_BERV_PLUS)
  (I_BERV_MINUS)
  (I_BERV_FIXED 1)
  (I_BERV_ELASTIC 4)
  (I_BERV_ELASTIC_PLUS)
  (I_BERV_ELASTIC_MINUS)
  (I_BERV_NONLINEAR)
  (I_BERV_ELASTIC_REDUCED)
  (I_BERV_ELASTIC_REDUCED_PLUS)
  (I_BERV_ELASTIC_REDUCED_MINUS))

(define-incr-enum IRobotBarSectionNonstdDataValue
  (I_BSNDV_BOX_H)
  (I_BSNDV_BOX_B)
  (I_BSNDV_BOX_TF)
  (I_BSNDV_BOX_TW)
  (I_BSNDV_I_H 0)
  (I_BSNDV_I_B)
  (I_BSNDV_I_TF)
  (I_BSNDV_I_TW)
  (I_BSNDV_II_H 0)
  (I_BSNDV_II_TW)
  (I_BSNDV_II_TF1)
  (I_BSNDV_II_TF2)
  (I_BSNDV_II_B1)
  (I_BSNDV_II_B2)
  (I_BSNDV_TUBE_D 0)
  (I_BSNDV_TUBE_T)
  (I_BSNDV_RECT_B 0)
  (I_BSNDV_RECT_H)
  (I_BSNDV_RECT_T)
  (I_BSNDV_C_H 0)
  (I_BSNDV_C_B)
  (I_BSNDV_C_TF)
  (I_BSNDV_C_TW)
  (I_BSNDV_L_H 0)
  (I_BSNDV_L_B)
  (I_BSNDV_L_TF)
  (I_BSNDV_L_TW)
  (I_BSNDV_Z_H 0)
  (I_BSNDV_Z_B)
  (I_BSNDV_Z_TF)
  (I_BSNDV_Z_TW)
  (I_BSNDV_T_H 0)
  (I_BSNDV_T_B)
  (I_BSNDV_T_TF)
  (I_BSNDV_T_TW)
  (I_BSNDV_H_H 0)
  (I_BSNDV_H_B)
  (I_BSNDV_H_B1)
  (I_BSNDV_H_TF)
  (I_BSNDV_H_TW)
  (I_BSNDV_XT_H 0)
  (I_BSNDV_XT_H1)
  (I_BSNDV_XT_B)
  (I_BSNDV_XT_TF)
  (I_BSNDV_XT_TW)
  (I_BSNDV_XI_H 0)
  (I_BSNDV_XI_H1)
  (I_BSNDV_XI_B)
  (I_BSNDV_XI_TF)
  (I_BSNDV_XI_TW)
  (I_BSNDV_DRECT_B 0)
  (I_BSNDV_DRECT_H)
  (I_BSNDV_DRECT_D)
  (I_BSNDV_CROSS_P1_L 0)
  (I_BSNDV_CROSS_P2_L)
  (I_BSNDV_CROSS_P3_L)
  (I_BSNDV_CROSS_P4_L)
  (I_BSNDV_CROSS_P1_T)
  (I_BSNDV_CROSS_P2_T)
  (I_BSNDV_CROSS_P3_T)
  (I_BSNDV_CROSS_P4_T)
  (I_BSNDV_HOLE_B 0)
  (I_BSNDV_HOLE_H)
  (I_BSNDV_HOLE_X)
  (I_BSNDV_HOLE_Z)
  (I_BSNDV_BOX_2_H 0)
  (I_BSNDV_BOX_2_B)
  (I_BSNDV_BOX_2_B1)
  (I_BSNDV_BOX_2_TF)
  (I_BSNDV_BOX_2_TW)
  (I_BSNDV_POLYGONAL_N 0)
  (I_BSNDV_POLYGONAL_D)
  (I_BSNDV_POLYGONAL_T)
  (I_BSNDV_POLYGONAL_D_IS_INT)
  (I_BSNDV_BOX_3_H 0)
  (I_BSNDV_BOX_3_B)
  (I_BSNDV_BOX_3_TW)
  (I_BSNDV_BOX_3_TF)
  (I_BSNDV_BOX_3_B1)
  (I_BSNDV_BOX_3_B2)
  (I_BSNDV_BOX_3_TF2))

(define-incr-enum IRobotCaseNature
  I_CN_PERMANENT
  I_CN_EXPLOATATION
  I_CN_WIND
  I_CN_SNOW
  I_CN_TEMPERATURE
  I_CN_ACCIDENTAL
  I_CN_SEISMIC)

(define-incr-enum IRobotCaseAnalizeType
  (I_CAT_COMB_NONLINEAR_INCREMENTAL -5)
  (I_CAT_COMB_BUCKLING)
  (I_CAT_COMB_NONLINEAR_BUCKLING)
  (I_CAT_COMB_INCREMENTAL)
  (I_CAT_COMB_NONLINEAR)
  (I_CAT_COMB)
  (I_CAT_STATIC_LINEAR)
  (I_CAT_STATIC_NONLINEAR)
  (I_CAT_STATIC_INCREMENTAL)
  (I_CAT_STATIC_FLAMBEMENT)
  (I_CAT_STATIC_LINEAR_AUXILIARY)
  (I_CAT_STATIC_NONLINEAR_INCREMENTAL)
  (I_CAT_STATIC_NONLINEAR_FLAMBEMENT)
  (I_CAT_STATIC_NONLINEAR_MODAL)
  (I_CAT_DYNAMIC_MODAL 11)
  (I_CAT_DYNAMIC_SPECTRAL)
  (I_CAT_DYNAMIC_SEISMIC)
  (I_CAT_DYNAMIC_HARMONIC)
  (I_CAT_TEMPORAR 20)
  (I_CAT_MOBILE_MAIN 30)
  (I_CAT_MOBILE_DERIVED)
  (I_CAT_NULL 99)
  (I_CAT_COMB_CODE -12)
  (I_CAT_STATIC_BUCKLING 4)
  (I_CAT_STATIC_NONLINEAR_BUCKLING 7)
  (I_CAT_DYNAMIC_NONLINEAR_MODAL_WITH_STATIC_FORCE)
  (I_CAT_TIME_HISTORY 20)
  (I_CAT_PUSH_OVER 25)
  (I_CAT_DYNAMIC_FRF 15)
  (I_CAT_DYNAMIC_FOOTFALL)
  (I_CAT_STATIC_ELF_SEISMIC 9))

(define-incr-enum IRobotLoadRecordType
  (I_LRT_NODE_FORCE)
  (I_LRT_NODE_DISPLACEMENT)
  (I_LRT_BAR_DILATATION)
  (I_LRT_BAR_FORCE_CONCENTRATED)
  (I_LRT_BAR_MOMENT_DISTRIBUTED)
  (I_LRT_BAR_UNIFORM)
  (I_LRT_BAR_TRAPEZOIDALE)
  (I_LRT_BAR_DEAD)
  (I_LRT_BAR_THERMAL)
  (I_LRT_LINEAR 21)
  (I_LRT_LINEAR_3D 19)
  (I_LRT_NODE_AUXILIARY)
  (I_LRT_POINT_AUXILIARY 23)
  (I_LRT_IN_3_POINTS 22)
  (I_LRT_PRESSURE 24)
  (I_LRT_THERMAL_IN_3_POINTS)
  (I_LRT_IN_CONTOUR 28)
  (I_LRT_NODE_FORCE_MASS 30)
  (I_LRT_BAR_FORCE_CONCENTRATED_MASS 33)
  (I_LRT_BAR_UNIFORM_MASS 35)
  (I_LRT_BAR_TRAPEZOIDALE_MASS)
  (I_LRT_MASS_ACTIVATION 39)
  (I_LRT_SPECTRUM_VALUE)
  (I_LRT_UNIFORM 26)
  (I_LRT_THERMAL 8)
  (I_LRT_NODE_FORCE_IN_POINT 23)
  (I_LRT_LINEAR_ON_EDGES 69)
  (I_LRT_DEAD 7)
  (I_LRT_SURFACE_ON_OBJECT 70)
  (I_LRT_MOBILE_POINT_FORCE 53)
  (I_LRT_MOBILE_DISTRIBUTED 55)
  (I_LRT_NODE_VELOCITY 10)
  I_LRT_NODE_ACCELERATION)

(define-incr-enum IRobotNodeForceRecordValues
  I_NFRV_FX
  I_NFRV_FY
  I_NFRV_FZ
  I_NFRV_CX
  I_NFRV_CY
  I_NFRV_CZ
  (I_NFRV_ALPHA 8)
  I_NFRV_BETA
  I_NFRV_GAMMA)